import { Role, Participant, Gender } from './types';

export const PARTICIPANTS: Participant[] = [
  { id: '1', name: 'Aaron Harris', role: Role.Dev, gender: Gender.Male },
  { id: '2', name: 'Abisola Fatokun', role: Role.Facilitator, gender: Gender.Female },
  { id: '3', name: 'Adunni', role: Role.Facilitator, gender: Gender.Female },
  { id: '4', name: 'Alyssa White', role: Role.ProductManager, gender: Gender.Female },
  { id: '5', name: 'Annette Joseph MBE', role: Role.DeliveryManager, gender: Gender.Female },
  { id: '6', name: 'Ayesha Nicholls', role: Role.Communications, gender: Gender.Female },
  { id: '7', name: 'Blessing', role: Role.Facilitator, gender: Gender.Female },
  { id: '8', name: 'Cara Jean-Baptiste', role: Role.Communications, gender: Gender.Female },
  { id: '9', name: 'Christopher corbin', role: Role.Infrastructure, gender: Gender.Male },
  { id: '10', name: 'Efeosasere Okoro', role: Role.DeliveryManager, gender: Gender.Male },
  { id: '11', name: 'Fabian', role: Role.ContentWriter, gender: Gender.Female },
  { id: '12', name: 'Gavin Wye', role: Role.ProductManager, gender: Gender.Male },
  { id: '13', name: 'Isaiah Carrington', role: Role.Dev, gender: Gender.Male },
  { id: '14', name: 'Joshua Cummins', role: Role.Infrastructure, gender: Gender.Male },
  { id: '15', name: 'Kareem Tyrell', role: Role.ProductManager, gender: Gender.Male },
  { id: '16', name: 'Kelly Roberts', role: Role.DeliveryManager, gender: Gender.Female },
  { id: '17', name: 'Kristin Ruck', role: Role.Designer, gender: Gender.Female },
  { id: '18', name: 'Laron Maughn', role: Role.Dev, gender: Gender.Male },
  { id: '19', name: 'Leann King', role: Role.DeliveryManager, gender: Gender.Female },
  { id: '20', name: 'Mark Boyce', role: Role.DeliveryManager, gender: Gender.Male },
  { id: '21', name: 'Shakira Perry', role: Role.ContentWriter, gender: Gender.Female },
  { id: '22', name: 'Shannon', role: Role.Dev, gender: Gender.Male },
  { id: '23', name: 'Shari Hannaway-Cave', role: Role.Communications, gender: Gender.Female },
  { id: '24', name: 'Shayla Murrell', role: Role.Communications, gender: Gender.Female },
  { id: '25', name: 'Sherri Cumberbatch', role: Role.Communications, gender: Gender.Female },
  { id: '26', name: 'Tarika Birch', role: Role.Dev, gender: Gender.Female },
  { id: '27', name: 'Tracy Forde-Catlyn', role: Role.DeliveryManager, gender: Gender.Female },
  { id: '28', name: 'Tyrell Wade', role: Role.Designer, gender: Gender.Male },
  { id: '29', name: 'Udochukwu Odibo', role: Role.Designer, gender: Gender.Male },
];
